version: '3.9'
services: 
 user_service:
  build: Docker/user-service
  image: user-img:1.0
  ports:
  - "51173:80"
  networks:
  - homiegainz
  depends_on:
  - eureka

 challenge_service:
  build: Docker/challenge-service
  image: challenge-img:1.0
  ports:
  - "51174:80"
  networks:
  - homiegainz
  depends_on:
  - eureka

 exercise-service:
  build: Docker/exercise-service
  image: exercise-img:1.0
  ports:
  - "51175:80"
  networks:
  - homiegainz
  depends_on:
  - eureka

 friendship-service:
  build: Docker/friendship-service
  image: friendship-img:1.0
  ports:
  - "51176:80"
  networks:
  - homiegainz
  depends_on:
  - eureka

 mealplan-service:
  build: Docker/mealplan-service
  image: mealplan-img:1.0
  ports:
  - "51177:80"
  networks:
  - homiegainz
  depends_on:
  - eureka
   
 meal-service:
  build: Docker/meal-service
  image: meal-img:1.0
  ports:
  - "51178:80"
  networks:
  - homiegainz
  depends_on:
  - eureka

 workoutplan-service:
  build: Docker/workoutplan-service
  image: workoutplan-img:1.0
  ports:
  - "51179:80"
  networks:
  - homiegainz
  depends_on:
  - eureka

 workout-service:
  build: Docker/workout-service
  image: workout-img:1.0
  ports:
  - "51180:80"
  networks:
  - homiegainz
  depends_on:
  - eureka

 applicationDb:
  build: Docker/appdb
  image: appdb-img:1.0
  ports:
  - "51172:80"
  networks:
  - homiegainz
  depends_on:
  - eureka

 eureka:
  container_name: eureka
  image: steeltoeoss/eureka-server
  ports:
  - "8761:8761"
  networks:
  - homiegainz

 HomiegainzDb:
  image: "mcr.microsoft.com/mssql/server:2019-latest"
  container_name: HomieGainzDb
  environment:
   - ACCEPT_EULA=Y
   - MSSQL_SA_PASSWORD=abc123!!@
  ports:
  - "1432:1433"
  networks:
  - homiegainz

networks:
 homiegainz:
  name: "homiegainz" 